Repository rakshitmehra/Quiz-application, pull requests merged in 2022-10, with the labels that each got.

#7 License
  LICENSE
Labels: good first issue, hacktoberfest-accepted, open-source

#6 Try to laugh challenge website
  Try to laugh challenge/images/ik-logo-dark-grey-bg.jpg
  Try to laugh challenge/index.html
  Try to laugh challenge/script.js
  Try to laugh challenge/style.css
Labels: good first issue, hacktoberfest-accepted, open-source

#10 Added animation
  index.html
Labels: good first issue, hacktoberfest-accepted

#12 Binary Trees Questions
  .idea/.gitignore
  .idea/Quiz.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Programming Questionns/binaryTrees/binaryTrees.md
Labels: hacktoberfest-accepted

#14 A login Page
  A login Page/A login Page/index.html
  A login Page/A login Page/main.js
  A login Page/A login Page/roject (1).jpg
  A login Page/A login Page/roject.jpg
  A login Page/A login Page/style.css
  A login Page/A login Page/woman.png
Labels: good first issue, hacktoberfest-accepted

#15 number-game
  game/number-game
Labels: good first issue, hacktoberfest-accepted

#16 Credit Card Validator
  Credit Card Validator/credit card validator solution.cpp
Labels: hacktoberfest-accepted

#18 Make the website responsive
  Try to laugh challenge/index.html
  Try to laugh challenge/responsive.css
  app.js
  index.html
  responsive.css
Labels: hacktoberfest-accepted, open-source

#19 Adding python Program
  Face Recognition/facerecognition.py
  Face Recognition/haarcascade_frontalface_default.xml
Labels: good first issue, hacktoberfest-accepted

#20 Added C++ programs
  C++ Programs/Linkedlist.cpp
  C++ Programs/Minimum_swaps.cpp
  C++ Programs/Rightview.cpp
  C++ Programs/Rotate_image.cpp
  C++ Programs/balife.cpp
  C++ Programs/hashmap.cpp
  C++ Programs/length_longest_subarray.cpp
  C++ Programs/maximum_sum.cpp
  C++ Programs/rainwatertrapping.cpp
Labels: hacktoberfest-accepted

#23 Add files via upload
  calculator.cpp
Labels: hacktoberfest-accepted

#22 Create AVLTreeInsertion.cpp
  AVLTreeInsertion.cpp
Labels: hacktoberfest-accepted

#25 Create Longest Palindromic Substring.cpp
  Longest Palindromic Substring.cpp
Labels: hacktoberfest-accepted

#26 Linked List Basic Program Added
  C++/C++ Programs/linked1.cpp
Labels: good first issue, hacktoberfest-accepted

#27 Create Bellman Ford program
  C++/C++ Programs/Bellman Ford - Shortest distance from Source having Negative Edge Weight but NO Negative Cycle.cpp
Labels: good first issue, hacktoberfest-accepted

#29 amstrong number issue:#17
  C++/C++ Programs/hack1.cpp
Labels: good first issue, hacktoberfest-accepted

#31 Create Maximum_sum_of_hour_glass
  C++/C++ Programs/Maximum_Sum_of_an_Hourglass.cpp
Labels: good first issue, hacktoberfest-accepted

#32 Longest palindromic substring
  C++/C++ Programs/longestpalindromicstring.cpp
Labels: good first issue, hacktoberfest-accepted

#33 Added a quick sort program using c++
  C++/C++ Programs/Quick_sort.cpp
Labels: good first issue, hacktoberfest-accepted

#34 Added a c++ program to find perfect number
  C++/Find_Perfect_number.cpp
Labels: good first issue, hacktoberfest-accepted

#35 Adding Face Recognition Program
  OpenCV/Face Recognition/facerecognition.py
  OpenCV/Face Recognition/haarcascade_frontalface_default.xml
  Programming Questionns/Array/C++/bubblesortobj.cpp
Labels: good first issue, hacktoberfest-accepted

#36 Adding Reverse the array Program
  Programming Questionns/Array/C++/Reverse.cpp
Labels: good first issue, hacktoberfest-accepted

#37 Median of Two Sorted Arrays.cpp added
  C++/C++ Programs/Median-of-Two-Sorted-Arrays.cpp
Labels: hacktoberfest-accepted

#39 Create Spiral_Matrix.cpp
  C++/C++ Programs/Spiral_Matrix.cpp
Labels: hacktoberfest-accepted

#40 Add files via upload
  calculator.cpp
Labels: hacktoberfest-accepted

#41 Updatad styles of Submit button
  assests/css/style.css
Labels: hacktoberfest-accepted

#42 Tree Implementation
  C++/C++ Programs/Tree2.cpp
Labels: hacktoberfest-accepted

#47 Update longestpalindromicstring.cpp
  C++/C++ Programs/longestpalindromicstring.cpp
Labels: hacktoberfest-accepted

#48 Create diameter of binary tree .cpp
  C++/C++ Programs/diameter of binary tree .cpp
Labels: hacktoberfest-accepted
